#!/usr/bin/env python3
"""
export_easylanguage.py
Turns a StrategySpec into an EasyLanguage-style starting point, deliberately
written in the same Input:/vars:/POI/SPACE/FILTER shape as the uploaded
`breakout_samples.md` (BREAKOUT_TRADING_REVOLUTION_CODE_1/2 and DowBreaker).

This is a TEMPLATE, not a compiler -- it's meant to save you the first draft
of translating a winning idea into TradeStation/MultiCharts syntax, the same
way the source material's own code samples are hand-written references, not
auto-generated output. Verify it compiles and behaves as intended in your
own platform before trusting it with money. Same disclaimer as the source
material: educational starting point only, not a trading recommendation.
"""
from __future__ import annotations
from generator import StrategySpec

_POI_EL = {
    "prev_close":       "CloseD(1)",
    "prev_high":         "HighD(1)",
    "prev_low":          "LowD(1)",
    "session_open":      "OpenD(0)",
    "sma20":             "Average(Close, 20)",
    "sma50":             "Average(Close, 50)",
    "donchian_high20":   "Highest(High, 20)",
    "donchian_low20":    "Lowest(Low, 20)",
    "highest_high_10":   "Highest(High, 10)",
    "lowest_low_10":     "Lowest(Low, 10)",
    # true intraday running HOD/LOD; EasyLanguage has no built-in
    # "high so far today", so this reimplements it directly. Harmless on
    # daily bars (Date <> Date[1] is always true, so it just resets every bar).
    "hod_running":       "HighD(0)",
    "lod_running":       "LowD(0)",
}

_FILTER_EL = {
    "none":                  None,
    "adx_trend":             "ADX(14) > {p}",
    "adx_below":              "ADX(25) < {p}",
    "adx_master_filter":       "ADX(15) > 20  // fixed, non-optimized universal filter -- do not vary this one",
    "close_above_sma100":      "Close > Average(Close, 100)",
    "close_below_sma100":      "Close < Average(Close, 100)",
    "atr_expansion":            "AvgTrueRange(10) > AvgTrueRange(50) * {p}",
    "atr_contraction":          "AvgTrueRange(10) < AvgTrueRange(50) * {p}",
    "volume_spike":              "Volume > Average(Volume, 20) * {p}",
    "shallow_pullback_long":      "(Highest(High, 10) - Close) < {p} * AvgTrueRange(14)",
    "shallow_pullback_short":      "(Close - Lowest(Low, 10)) < {p} * AvgTrueRange(14)",
    # mirrors breakout_samples.md CODE_2's literal TimeFilter style
    # (time > 830 and time <= 930) using EasyLanguage's native Time (HHMM),
    # split into session thirds via the SessionStart/SessionEnd inputs
    # rather than hardcoding specific exchange hours.
    "time_window_open":    "Time >= SessionStart and Time < SessionStart + (SessionEnd - SessionStart) / 3",
    "time_window_mid":      "Time >= SessionStart + (SessionEnd - SessionStart) / 3 "
                              "and Time < SessionStart + 2 * (SessionEnd - SessionStart) / 3",
    "time_window_close":     "Time >= SessionStart + 2 * (SessionEnd - SessionStart) / 3 and Time <= SessionEnd",
}

_TIME_WINDOW_FILTERS = {"time_window_open", "time_window_mid", "time_window_close"}


def _fmt_filter(spec: StrategySpec) -> str | None:
    template = _FILTER_EL[spec.filter_type]
    if template is None:
        return None
    return template.format(p=spec.filter_param) if "{p}" in template else template


def to_easylanguage(spec: StrategySpec, market: str = "YOUR_MARKET",
                      timeframe: str = "YOUR_TIMEFRAME") -> str:
    poi_expr = _POI_EL[spec.poi]
    direction_word = "Long" if spec.direction == "long" else "Short"
    filter_expr = _fmt_filter(spec)
    op = "+" if spec.direction == "long" else "-"
    order_word = "buy" if spec.direction == "long" else "sellshort"
    stop_word = "stop" if spec.direction == "long" else "stop"

    lines = []
    lines.append("{")
    lines.append(f"Generated by Breakout Setup Generator -- strategy_id {spec.strategy_id}")
    lines.append("Example code only! NOT actual trading strategy!")
    lines.append("THIS CODE IS FOR EDUCATIONAL PURPOSES ONLY. Verify before using.")
    lines.append(f"MARKET: {market}   TIMEFRAME: {timeframe}   DIRECTION: {direction_word}")
    lines.append(f"DNA: {spec.dna}")
    lines.append("}")
    lines.append("")
    lines.append("Inputs:")
    input_parts = [f"Fract({spec.distance_mult})"]
    if spec.filter_param is not None:
        input_parts.append(f"Filter_Param({spec.filter_param})")
    if spec.exit_type == "atr_stop_target":
        input_parts.append(f"StopMult({spec.stop_mult})")
        input_parts.append(f"TargetMult({spec.target_mult})")
    elif spec.exit_type == "poi_anchored_stop":
        input_parts.append(f"TargetMult({spec.target_mult})")
    elif spec.exit_type == "time_exit":
        input_parts.append(f"HoldDays({spec.hold_days})")
    if spec.filter_type in _TIME_WINDOW_FILTERS:
        input_parts.append("SessionStart(930)")  # HHMM, edit for your market's hours
        input_parts.append("SessionEnd(1530)")
    lines.append("    " + ", ".join(input_parts) + ";")
    lines.append("")
    lines.append("Vars:")
    varnames = ["POI(0)", "SPACE(0)", f"myBreakout{direction_word}(0)", "ATR(0)"]
    if filter_expr is not None:
        varnames.append("FILTER(false)")
    lines.append("    " + ", ".join(varnames) + ";")
    lines.append("")
    lines.append("// Point Of Initiation")
    lines.append(f"POI = {poi_expr};")
    lines.append("")
    lines.append("// ATR / SPACE (distance from the POI)")
    lines.append(f"ATR = AvgTrueRange({spec.atr_period});")
    lines.append("SPACE = Fract * ATR;")
    lines.append("")
    lines.append(f"// The BreakoutLevel (POI {op} SPACE)")
    lines.append(f"myBreakout{direction_word} = POI {op} SPACE;")
    lines.append("")
    if filter_expr is not None:
        lines.append("// Filter")
        lines.append(f"FILTER = {filter_expr};")
        lines.append("")
        entry_cond = "marketposition = 0 and FILTER"
    else:
        entry_cond = "marketposition = 0"
    lines.append("// Entry Condition")
    lines.append(f"If {entry_cond}")
    lines.append(f"    then {order_word} next bar myBreakout{direction_word} {stop_word};")
    lines.append("")
    lines.append("// Exit")
    if spec.exit_type == "atr_stop_target":
        lines.append("myStop = StopMult * ATR;")
        lines.append("myTarget = TargetMult * ATR;")
        if spec.direction == "long":
            lines.append("if marketposition = 1 then Sell next bar at EntryPrice - myStop stop;")
            lines.append("if marketposition = 1 then Sell next bar at EntryPrice + myTarget limit;")
        else:
            lines.append("if marketposition = -1 then BuyToCover next bar at EntryPrice + myStop stop;")
            lines.append("if marketposition = -1 then BuyToCover next bar at EntryPrice - myTarget limit;")
    elif spec.exit_type == "poi_anchored_stop":
        lines.append("// stop sits at the POI level itself (a real support/resistance line),")
        lines.append("// not an ATR multiple -- only the target is tunable")
        lines.append("myTarget = TargetMult * ATR;")
        if spec.direction == "long":
            lines.append("if marketposition = 1 then Sell next bar at POI stop;")
            lines.append("if marketposition = 1 then Sell next bar at EntryPrice + myTarget limit;")
        else:
            lines.append("if marketposition = -1 then BuyToCover next bar at POI stop;")
            lines.append("if marketposition = -1 then BuyToCover next bar at EntryPrice - myTarget limit;")
    elif spec.exit_type == "time_exit":
        lines.append("if marketposition <> 0 and BarsSinceEntry >= HoldDays")
        lines.append("    then Sell/BuyToCover next bar at market;  // time_exit")
    else:  # eod_exit -- the samples' own literal pattern
        lines.append("// Exit at the end of the day (same pattern as the uploaded samples)")
        lines.append("if marketposition <> 0 then setexitonclose;")
    lines.append("")
    lines.append("// Optional hard backstop -- uncomment and size for your market/point value")
    lines.append("// Setstoploss(1500);")

    return "\n".join(lines)


def export_top_strategies(specs: list[StrategySpec], out_dir: str, market: str = "YOUR_MARKET",
                            timeframe: str = "YOUR_TIMEFRAME") -> list[str]:
    import os
    os.makedirs(out_dir, exist_ok=True)
    paths = []
    for spec in specs:
        code = to_easylanguage(spec, market=market, timeframe=timeframe)
        path = os.path.join(out_dir, f"{spec.strategy_id}.el.txt")
        with open(path, "w") as f:
            f.write(code)
        paths.append(path)
    return paths
