#!/usr/bin/env python3
"""
export_pinescript.py
Same idea as export_easylanguage.py / export_afl.py, but rendered as
TradingView Pine Script v5 `strategy()` code. Same disclaimer: a
first-draft TEMPLATE to save you the translation work, not a compiler --
verify it compiles and behaves as intended on TradingView before trusting
it with money.
"""
from __future__ import annotations
from generator import StrategySpec

# Pine has no built-in ta.adx(); the idiomatic way is [+DI, -DI, ADX] = ta.dmi(len, len)
_POI_PINE = {
    "prev_close":       "close[1]",
    "prev_high":         "high[1]",
    "prev_low":          "low[1]",
    "session_open":      "open",
    "sma20":             "ta.sma(close, 20)[1]",
    "sma50":             "ta.sma(close, 50)[1]",
    "donchian_high20":   "ta.highest(high, 20)[1]",
    "donchian_low20":    "ta.lowest(low, 20)[1]",
    "highest_high_10":   "ta.highest(high, 10)[1]",
    "lowest_low_10":     "ta.lowest(low, 10)[1]",
}

# true intraday running HOD/LOD: Pine has no built-in "high so far today", so
# this reimplements it with the standard new-day-detection pattern. Needs
# multi-line setup before the POI assignment, not just an inline expression.
_SESSION_POI_PINE = {
    "hod_running": (
        'newDay = ta.change(time("D")) != 0\n'
        'var float dayHigh = na\n'
        'dayHigh := newDay ? high : math.max(nz(dayHigh), high)',
        "dayHigh[1]"),
    "lod_running": (
        'newDay = ta.change(time("D")) != 0\n'
        'var float dayLow = na\n'
        'dayLow := newDay ? low : math.min(nz(dayLow), low)',
        "dayLow[1]"),
}


def _adx_line(period: int, varname: str) -> str:
    return f"[_, _, {varname}] = ta.dmi({period}, {period})"


_FILTER_PINE = {
    # each entry: (extra_lines_fn(spec) -> list[str] | None, condition_template)
    "none": (None, None),
    "adx_trend": (lambda s: [_adx_line(14, "adxVal")], "adxVal > {p}"),
    "adx_below": (lambda s: [_adx_line(25, "adxVal")], "adxVal < {p}"),
    "adx_master_filter": (lambda s: [_adx_line(15, "adxVal")],
                           "adxVal > 20  // fixed, non-optimized universal filter -- do not vary this one"),
    "close_above_sma100": (None, "close > ta.sma(close, 100)"),
    "close_below_sma100": (None, "close < ta.sma(close, 100)"),
    "atr_expansion": (None, "ta.atr(10) > ta.atr(50) * {p}"),
    "atr_contraction": (None, "ta.atr(10) < ta.atr(50) * {p}"),
    "volume_spike": (None, "volume > ta.sma(volume, 20) * {p}"),
    "shallow_pullback_long": (None, "(ta.highest(high, 10)[1] - close[1]) < {p} * ta.atr(14)"),
    "shallow_pullback_short": (None, "(close[1] - ta.lowest(low, 10)[1]) < {p} * ta.atr(14)"),
    # mirrors breakout_samples.md CODE_2's TimeFilter (Test_Hour buckets) via
    # minutes-since-midnight thirds instead of hardcoded exchange hours.
    "time_window_open": (
        lambda s: ["minOfDay = hour * 60 + minute",
                    "sessionThird = (sessionEndMin - sessionStartMin) / 3"],
        "minOfDay >= sessionStartMin and minOfDay < sessionStartMin + sessionThird"),
    "time_window_mid": (
        lambda s: ["minOfDay = hour * 60 + minute",
                    "sessionThird = (sessionEndMin - sessionStartMin) / 3"],
        "minOfDay >= sessionStartMin + sessionThird and minOfDay < sessionStartMin + 2 * sessionThird"),
    "time_window_close": (
        lambda s: ["minOfDay = hour * 60 + minute",
                    "sessionThird = (sessionEndMin - sessionStartMin) / 3"],
        "minOfDay >= sessionStartMin + 2 * sessionThird and minOfDay <= sessionEndMin"),
}

_TIME_WINDOW_FILTERS = {"time_window_open", "time_window_mid", "time_window_close"}


def _filter_parts(spec: StrategySpec):
    extra_fn, template = _FILTER_PINE[spec.filter_type]
    if template is None:
        return [], None
    extra_lines = extra_fn(spec) if extra_fn else []
    cond = template.format(p=spec.filter_param) if "{p}" in template else template
    return extra_lines, cond


def to_pinescript(spec: StrategySpec, market: str = "YOUR_MARKET", timeframe: str = "YOUR_TIMEFRAME") -> str:
    poi_setup = None
    if spec.poi in _SESSION_POI_PINE:
        poi_setup, poi_expr = _SESSION_POI_PINE[spec.poi]
    else:
        poi_expr = _POI_PINE[spec.poi]
    is_long = spec.direction == "long"
    op = "+" if is_long else "-"
    extra_lines, filter_cond = _filter_parts(spec)
    strategy_dir = "strategy.long" if is_long else "strategy.short"
    entry_id = "Long" if is_long else "Short"

    lines = []
    lines.append("//@version=5")
    lines.append(f'strategy("BSG {spec.strategy_id}", overlay=true, '
                  "default_qty_type=strategy.percent_of_equity, default_qty_value=10)")
    lines.append(f"// Generated by Breakout Setup Generator -- strategy_id {spec.strategy_id}")
    lines.append("// Example code only! NOT actual trading strategy!")
    lines.append("// THIS CODE IS FOR EDUCATIONAL PURPOSES ONLY. Verify before using.")
    lines.append(f"// MARKET: {market}   TIMEFRAME: {timeframe}   DIRECTION: {entry_id.upper()}")
    lines.append(f"// DNA: {spec.dna}")
    lines.append("")
    lines.append(f"fract = input.float({spec.distance_mult}, \"Distance (x ATR)\")")
    if spec.exit_type == "atr_stop_target":
        lines.append(f"stopMult = input.float({spec.stop_mult}, \"Stop (x ATR)\")")
        lines.append(f"targetMult = input.float({spec.target_mult}, \"Target (x ATR)\")")
    elif spec.exit_type == "poi_anchored_stop":
        lines.append(f"targetMult = input.float({spec.target_mult}, \"Target (x ATR)\")")
    elif spec.exit_type == "time_exit":
        lines.append(f"holdBars = input.int({spec.hold_days}, \"Hold (bars)\")")
    if spec.filter_type in _TIME_WINDOW_FILTERS:
        lines.append('sessionStartMin = input.int(570, "Session start (minutes since midnight)")   // 09:30')
        lines.append('sessionEndMin = input.int(930, "Session end (minutes since midnight)")        // 15:30')
    lines.append("")
    lines.append("// Point Of Initiation")
    if poi_setup is not None:
        lines.append(poi_setup)
    lines.append(f"poi = {poi_expr}")
    lines.append("")
    lines.append("// ATR / space (distance from the POI)")
    lines.append(f"atrVal = ta.atr({spec.atr_period})")
    lines.append("space = fract * atrVal")
    lines.append("")
    lines.append(f"// The BreakoutLevel (POI {op} space)")
    lines.append(f"breakoutLevel = poi {op} space")
    lines.append("")
    for ln in extra_lines:
        lines.append(ln)
    if filter_cond is not None:
        lines.append(f"filterCond = {filter_cond}")
    else:
        lines.append("filterCond = true")
    lines.append("")
    breakout_test = "close > breakoutLevel" if is_long else "close < breakoutLevel"
    lines.append("// Entry Condition")
    lines.append(f"entrySignal = {breakout_test} and filterCond and strategy.position_size == 0")
    lines.append(f'if entrySignal')
    lines.append(f'    strategy.entry("{entry_id}", {strategy_dir})')
    lines.append("")
    lines.append("// Exit")
    if spec.exit_type == "atr_stop_target":
        if is_long:
            lines.append("stopPrice = strategy.position_avg_price - stopMult * atrVal")
            lines.append("targetPrice = strategy.position_avg_price + targetMult * atrVal")
        else:
            lines.append("stopPrice = strategy.position_avg_price + stopMult * atrVal")
            lines.append("targetPrice = strategy.position_avg_price - targetMult * atrVal")
        lines.append(f'strategy.exit("Exit", "{entry_id}", stop=stopPrice, limit=targetPrice)')
    elif spec.exit_type == "poi_anchored_stop":
        lines.append("// stop sits at the POI level itself (a real support/resistance line),")
        lines.append("// not an ATR multiple -- only the target is tunable")
        if is_long:
            lines.append("stopPrice = poi")
            lines.append("targetPrice = strategy.position_avg_price + targetMult * atrVal")
        else:
            lines.append("stopPrice = poi")
            lines.append("targetPrice = strategy.position_avg_price - targetMult * atrVal")
        lines.append(f'strategy.exit("Exit", "{entry_id}", stop=stopPrice, limit=targetPrice)')
    elif spec.exit_type == "time_exit":
        lines.append("barsInTrade = strategy.opentrades > 0 ? "
                      "bar_index - strategy.opentrades.entry_bar_index(strategy.opentrades - 1) : 0")
        lines.append("if barsInTrade >= holdBars")
        lines.append(f'    strategy.close("{entry_id}")')
    else:  # eod_exit -- mirrors the samples' literal "setexitonclose" pattern
        lines.append("// close out at the end of the entry session (SetExitOnClose equivalent)")
        lines.append('newSessionExit = ta.change(time("D"))[1] != 0  // True on the first bar of a NEW session,')
        lines.append("                                                 // i.e. one bar after the prior session ended")
        lines.append("if newSessionExit and strategy.position_size != 0")
        lines.append(f'    strategy.close("{entry_id}")')
    lines.append("")
    lines.append("// Optional hard backstop -- uncomment and size for your market/point value")
    lines.append('// strategy.exit("Backstop", stop=strategy.position_avg_price - 1500 * syminfo.mintick)')

    return "\n".join(lines)


def export_top_strategies(specs: list[StrategySpec], out_dir: str, market: str = "YOUR_MARKET",
                            timeframe: str = "YOUR_TIMEFRAME") -> list[str]:
    import os
    os.makedirs(out_dir, exist_ok=True)
    paths = []
    for spec in specs:
        code = to_pinescript(spec, market=market, timeframe=timeframe)
        path = os.path.join(out_dir, f"{spec.strategy_id}.pine")
        with open(path, "w") as f:
            f.write(code)
        paths.append(path)
    return paths
