#!/usr/bin/env python3
"""
export_afl.py
Same idea as export_easylanguage.py, but rendered as AmiBroker Formula
Language (AFL) instead. Same disclaimer: a first-draft TEMPLATE to save you
the translation work, not a compiler -- verify it compiles and behaves as
intended in AmiBroker before trusting it with money.
"""
from __future__ import annotations
from generator import StrategySpec

_POI_AFL = {
    "prev_close":       "Ref(C, -1)",
    "prev_high":         "Ref(H, -1)",
    "prev_low":          "Ref(L, -1)",
    "session_open":      "O",
    "sma20":             "Ref(MA(C, 20), -1)",
    "sma50":             "Ref(MA(C, 50), -1)",
    "donchian_high20":   "Ref(HHV(H, 20), -1)",
    "donchian_low20":    "Ref(LLV(L, 20), -1)",
    "highest_high_10":   "Ref(HHV(H, 10), -1)",
    "lowest_low_10":     "Ref(LLV(L, 10), -1)",
}

# true intraday running HOD/LOD: AmiBroker's HighestSince/LowestSince reset
# whenever the trigger condition (a new session starting) fires, giving the
# running high/low SO FAR TODAY. Handled separately from _POI_AFL below
# since it needs a helper line before the POI assignment, not just an
# inline expression.
_SESSION_POI_AFL = {
    "hod_running": ("NewSession = Day() != Ref(Day(), -1);",
                     "Ref(HighestSince(NewSession, H), -1)"),
    "lod_running": ("NewSession = Day() != Ref(Day(), -1);",
                     "Ref(LowestSince(NewSession, L), -1)"),
}

_FILTER_AFL = {
    "none":                  None,
    "adx_trend":             "ADX(14) > {p}",
    "adx_below":              "ADX(25) < {p}",
    "adx_master_filter":       "ADX(15) > 20; // fixed, non-optimized universal filter -- do not vary this one",
    "close_above_sma100":      "C > MA(C, 100)",
    "close_below_sma100":      "C < MA(C, 100)",
    "atr_expansion":            "ATR(10) > ATR(50) * {p}",
    "atr_contraction":          "ATR(10) < ATR(50) * {p}",
    "volume_spike":              "V > MA(V, 20) * {p}",
    "shallow_pullback_long":      "(Ref(HHV(H, 10), -1) - Ref(C, -1)) < {p} * ATR(14)",
    "shallow_pullback_short":      "(Ref(C, -1) - Ref(LLV(L, 10), -1)) < {p} * ATR(14)",
    # mirrors breakout_samples.md CODE_2's literal TimeFilter style
    # (time > 830 and time <= 930) using AFL's native TimeNum() clock,
    # split into session thirds via the SessionStart/SessionEnd inputs
    # below rather than hardcoding specific exchange hours.
    "time_window_open":    "TimeNum() >= SessionStart AND TimeNum() < SessionStart + (SessionEnd - SessionStart) / 3",
    "time_window_mid":      "TimeNum() >= SessionStart + (SessionEnd - SessionStart) / 3 "
                              "AND TimeNum() < SessionStart + 2 * (SessionEnd - SessionStart) / 3",
    "time_window_close":     "TimeNum() >= SessionStart + 2 * (SessionEnd - SessionStart) / 3 AND TimeNum() <= SessionEnd",
}

_TIME_WINDOW_FILTERS = {"time_window_open", "time_window_mid", "time_window_close"}


def _fmt_filter(spec: StrategySpec) -> str | None:
    template = _FILTER_AFL[spec.filter_type]
    if template is None:
        return None
    return template.format(p=spec.filter_param) if "{p}" in template else template


def to_afl(spec: StrategySpec, market: str = "YOUR_MARKET", timeframe: str = "YOUR_TIMEFRAME") -> str:
    session_helper = None
    if spec.poi in _SESSION_POI_AFL:
        session_helper, poi_expr = _SESSION_POI_AFL[spec.poi]
    else:
        poi_expr = _POI_AFL[spec.poi]
    filter_expr = _fmt_filter(spec)
    op = "+" if spec.direction == "long" else "-"
    is_long = spec.direction == "long"
    entry_var, exit_var = ("Buy", "Sell") if is_long else ("Short", "Cover")

    lines = []
    lines.append("// Generated by Breakout Setup Generator -- "
                  f"strategy_id {spec.strategy_id}")
    lines.append("// Example code only! NOT actual trading strategy!")
    lines.append("// THIS CODE IS FOR EDUCATIONAL PURPOSES ONLY. Verify before using.")
    lines.append(f"// MARKET: {market}   TIMEFRAME: {timeframe}   "
                  f"DIRECTION: {'LONG' if is_long else 'SHORT'}")
    lines.append(f"// DNA: {spec.dna}")
    lines.append("")
    lines.append("SetOption(\"MaxOpenPositions\", 1);")
    lines.append(f"Fract = {spec.distance_mult};")
    if spec.filter_type in _TIME_WINDOW_FILTERS:
        lines.append("SessionStart = 093000; SessionEnd = 153000;  // HHMMSS, edit for your market's hours")
    lines.append("")
    lines.append("// Point Of Initiation")
    if session_helper is not None:
        lines.append(session_helper)
    lines.append(f"POI = {poi_expr};")
    lines.append("")
    lines.append("// ATR / SPACE (distance from the POI)")
    lines.append(f"ATRval = ATR({spec.atr_period});")
    lines.append("SPACE = Fract * ATRval;")
    lines.append("")
    lines.append(f"// The BreakoutLevel (POI {op} SPACE)")
    lines.append(f"BreakoutLevel = POI {op} SPACE;")
    lines.append("")
    if filter_expr is not None:
        lines.append("// Filter")
        lines.append(f"FilterCond = {filter_expr};")
        lines.append("")
        cond = "FilterCond AND " + ("Cross(C, BreakoutLevel)" if is_long else "Cross(BreakoutLevel, C)")
    else:
        cond = "Cross(C, BreakoutLevel)" if is_long else "Cross(BreakoutLevel, C)"
    lines.append("// Entry Condition (breaks through the level, filled next bar)")
    lines.append(f"{entry_var} = Ref({cond}, -1);")
    lines.append(f"{entry_var}Price = Open;")
    lines.append("")
    lines.append("// Exit")
    if spec.exit_type == "atr_stop_target":
        lines.append("StopMult = " + str(spec.stop_mult) + "; TargetMult = " + str(spec.target_mult) + ";")
        lines.append("ApplyStop(stopTypeLoss, stopModePoint, StopMult * ATRval, True);")
        lines.append("ApplyStop(stopTypeProfit, stopModePoint, TargetMult * ATRval, True);")
        lines.append(f"{exit_var} = 0;  // handled by ApplyStop() above")
    elif spec.exit_type == "poi_anchored_stop":
        lines.append("// stop sits at the POI level itself (a real support/resistance line),")
        lines.append("// not an ATR multiple -- only the target is tunable")
        lines.append(f"TargetMult = {spec.target_mult};")
        if is_long:
            lines.append("StopDistPts = Open - POI;  // distance from today's fill to the POI, in points")
        else:
            lines.append("StopDistPts = POI - Open;")
        lines.append("ApplyStop(stopTypeLoss, stopModePoint, StopDistPts, True);")
        lines.append("ApplyStop(stopTypeProfit, stopModePoint, TargetMult * ATRval, True);")
        lines.append(f"{exit_var} = 0;  // handled by ApplyStop() above")
    elif spec.exit_type == "time_exit":
        lines.append(f"HoldBars = {spec.hold_days};")
        lines.append(f"{exit_var} = BarsSince({entry_var}) >= HoldBars;")
    else:  # eod_exit -- mirrors the samples' literal "setexitonclose" pattern
        lines.append("// close out at the end of the entry session (SetExitOnClose equivalent)")
        lines.append("NewSessionExit = Day() != Ref(Day(), 1);  // True on the LAST bar of each session")
        lines.append(f"{exit_var} = NewSessionExit;")
    lines.append(f"{exit_var}Price = Open;")
    lines.append("")
    lines.append("// Optional hard backstop -- uncomment and size for your market/point value")
    lines.append("// ApplyStop(stopTypeLoss, stopModePoint, 1500, True);")

    return "\n".join(lines)


def export_top_strategies(specs: list[StrategySpec], out_dir: str, market: str = "YOUR_MARKET",
                            timeframe: str = "YOUR_TIMEFRAME") -> list[str]:
    import os
    os.makedirs(out_dir, exist_ok=True)
    paths = []
    for spec in specs:
        code = to_afl(spec, market=market, timeframe=timeframe)
        path = os.path.join(out_dir, f"{spec.strategy_id}.afl")
        with open(path, "w") as f:
            f.write(code)
        paths.append(path)
    return paths
